# Laboratorio 2

In [3]:
import numpy as np
from scipy import linalg

## Ejercicio 1

Dados dos NumPy array, `x` e `y` unidimensionales, construye su matriz de Cauchy `C`tal que 

(1 punto)

$$
    c_{ij} = \frac{1}{x_i - y_j}
$$

In [28]:
def cauchy_matrix(x, y):
    m = x.shape[0]
    n = y.shape[0]
    C = np.empty(shape=(m, n))
    for i in range(m):
        for j in range(n):
            C[i, j]= 1/(x[i]-y[j])
    return C

In [29]:
x = np.arange(10, 101, 10)
y = np.arange(5)
cauchy_matrix(x, y)

array([[0.1       , 0.11111111, 0.125     , 0.14285714, 0.16666667],
       [0.05      , 0.05263158, 0.05555556, 0.05882353, 0.0625    ],
       [0.03333333, 0.03448276, 0.03571429, 0.03703704, 0.03846154],
       [0.025     , 0.02564103, 0.02631579, 0.02702703, 0.02777778],
       [0.02      , 0.02040816, 0.02083333, 0.0212766 , 0.02173913],
       [0.01666667, 0.01694915, 0.01724138, 0.01754386, 0.01785714],
       [0.01428571, 0.01449275, 0.01470588, 0.01492537, 0.01515152],
       [0.0125    , 0.01265823, 0.01282051, 0.01298701, 0.01315789],
       [0.01111111, 0.01123596, 0.01136364, 0.01149425, 0.01162791],
       [0.01      , 0.01010101, 0.01020408, 0.01030928, 0.01041667]])

## Ejercicio 2

(1 punto)

Implementa la multiplicación matricial a través de dos ciclos `for`. Verifica que tu implementación está correcta y luego compara los tiempos de tu implementación versus la de NumPy.

In [56]:
def my_mul(A, B):
    m, n = A.shape
    p, q = B.shape
    if n != p:
        raise ValueError("Las dimensiones de las matrices no calzan!")
    C = np.empty(shape=(m,q))
    for i in range(m):
        for j in range(q):
            C[i, j] = np.sum(A[i]*B[:,j])
    return C

In [57]:
A = np.arange(15).reshape(-1, 5)
B = np.arange(20).reshape(5, -1)
my_mul(A, B)

array([[120., 130., 140., 150.],
       [320., 355., 390., 425.],
       [520., 580., 640., 700.]])

In [58]:
# Validation
np.allclose(my_mul(A, B), A @ B)

True

In [61]:
%%timeit
my_mul(A, B)

81.9 µs ± 4.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [62]:
%%timeit
A @ B

1.12 µs ± 53.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Ejercicio 3

(1 punto)

Crea una función que imprima todos los bloques contiguos de tamaño $3 \times 3$ para una matriz de $5 \times 5$.
Hint: Deben ser 9 bloques!

In [78]:
def three_times_three_blocks(A):
    m, n = A.shape
    counter = 1
    for i in range(m-2):# FIX ME #
        for j in range(n-2): # FIX ME #
            block = A[i:i+3,j:j+3] # FIX ME #
            print(f"Block {counter}:")
            print(block)
            print("\n")
            counter += 1

In [79]:
A = np.arange(1, 26).reshape(5, 5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [80]:
three_times_three_blocks(A)

Block 1:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


Block 2:
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


Block 3:
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


Block 4:
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


Block 5:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Block 6:
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


Block 7:
[[11 12 13]
 [16 17 18]
 [21 22 23]]


Block 8:
[[12 13 14]
 [17 18 19]
 [22 23 24]]


Block 9:
[[13 14 15]
 [18 19 20]
 [23 24 25]]




## Ejercicio 4

(1 punto)

Has tu propio implementación de la matriz de Hilbert de orden $n$ y luego compara los tiempos de ejecución versus la función [`scipy.linalg.hilbert`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.hilbert.html#scipy.linalg.hilbert). Finalmente, verifica que la inversa de tu implementación (utilizando `linalg.inv`) es idéntica a la obtenida con la función [`scipy.linalg.invhilbert`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.invhilbert.html#scipy.linalg.invhilbert).

In [81]:
def my_hilbert(n):
    H = np.empty((n, n))
    for i in range(n):
        for j in range(n):
            H[i,j]=1/(i+j+1)
    return H

In [88]:
H=my_hilbert(3)
H

array([[1.        , 0.5       , 0.33333333],
       [0.5       , 0.33333333, 0.25      ],
       [0.33333333, 0.25      , 0.2       ]])

In [83]:
%timeit my_hilbert(n)

6.48 µs ± 401 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [84]:
%timeit linalg.hilbert(n)

17 µs ± 330 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [103]:
# Verificacion inversas

np.allclose(
 linalg.inv(my_hilbert(9)), linalg.invhilbert(9)
)

True

Vuelve a probar pero con $n=10$. ¿Cambia algo? ¿Por qué podría ser?

__Respuesta:__  Debido a las limitaciones de las variables float, el error va creciendo para n muy grande, de modo que en algun momento el error deja de ser insignificante haciendo que cambie el valor de verdad, es decir, las matrices dejan de ser "insignificantemente" distintas y pasan a ser derechamente distintas